site_name: 'AVDASI 2 docs'
site_url: https://avdai2.github.io/docs
theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: flightlab
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: flightlab_dark
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
  - navigation.tracking
  - navigation.instant
  - navigation.search
  - navigation.search.highlight
  - navigation.search.suggestions
  - navigation.search.suggestions.highlight
  - navigation.tabs
  - navigation.sections
  - navigation.indexes
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  - content.code.expand
  - content.code.highlight
  - content.code.tabs
  - content.code.toggle
  - content.code.wrap
  - content.code.include
  - content.code.include.highlight
  - content.code.include.tabs
  - content.code.include.toggle
  - content.code.include.wrap
  - content.code.include.tabs
  - navigation.instant.progress
  - navigation.instant.preview
  - navigation.footer
  language: en
plugins:
 # - search
 # - literate-nav:
 #      nav_file: index.md
 #      implicit_index: true
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
markdown_extensions:
  - codehilite
  - footnotes
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UoBFlightLab

nav:
  - Home: index.md
  - Avionics:
    - avionics/index.md
    - Step-by-step MWE:
      - stepbystep/index.md
      - 1. Cube: stepbystep/1-cube.md
      - 2. Mission Planner: stepbystep/2-missionplanner.md
      - 3. Telemetry: stepbystep/3-telemetry.md
      - 4. Radio control: stepbystep/4-rc.md
      - 5. Data logging: stepbystep/5-datalog.md
      - 6. PyMAVLink: stepbystep/6-pymavlink.md
      - 7. I2C: stepbystep/7-i2c.md
      - 8. Luascript: stepbystep/8-lua.md
    - Example Code: avionics/examplecode.md